name: live_chatt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.1
  socket_io_client: ^2.0.0-beta.1
  dio: ^3.0.10

  google_fonts: ^1.1.1
  provider: ^4.3.2+2
  #page transition animation
  page_transition: '^1.1.7+2'
  #for some UI elements not very essential
  flui: 0.9.2
  #ios style date picker
  flutter_datetime_picker: ^1.4.0
  get_it: ^5.0.1
  #Height, age, range slider
  flutter_xlider: ^3.4.0

  #For reading icons at flutter
  flutter_svg: ^0.19.1
  flutter_icons: ^1.1.0

  #For showing loading icon when provider state changes
  loading_overlay: ^0.2.1
  flutter_styled_toast: ^1.4.0+1
  #Firebase Packages
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  flutter_facebook_auth: '^1.0.0'
  #firebase_database: ^4.4.0

  #maps and geolocation packages Using At MapPage
  google_maps_flutter: ^1.0.6
  google_place: ^0.3.3
  #getting user current location.
  geolocator: ^6.1.4

  #cluster manager for Google Maps. Using at MapPage
  google_maps_cluster_manager: ^0.2.0

  #to make bottom container for map Using at MapPage
  sliding_up_panel: ^1.0.2
  #To get LatLng from an address or to get Address From an LatLng
  geocoder: ^0.2.1

  #For swipe cards
  swipe_stack:
    ^1.0.0

    #For picking image from gallery
  image_picker: ^0.6.7+12
  #image_pickers: ^1.0.8+7

  #For creating timing indicator at match and likes page. Look at circular avatars
  percent_indicator: ^2.1.8

  #to make location search based on geohash.
  geoflutterfire: ^2.2.1

  #for local data managment. Key value pairs
  shared_preferences: ^0.5.12+4
  #cache image and loading indicator fo them
  cached_network_image: ^2.4.1

  #to draw chart. Used at venue detail page.
  fl_chart: ^0.12.0

  # Create unique id for firebase documents
  uuid: ^2.2.2

  path_provider: ^1.6.24
  #some stream operations do
  rxdart: ^0.24.1
  #Google recaptcha plugin
  flutter_recaptcha_v2: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
